"""Add response_time column to vulnerability

Revision ID: 1c0cde03cc2b
Revises: 4f0795be5b59
Create Date: 2025-10-11 17:40:18.991766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0cde03cc2b'
down_revision = '4f0795be5b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_column('response_time')

    # ### end Alembic commands ###
