"""add otp and trusted device to user

Revision ID: 3159ca256c18
Revises: 
Create Date: 2025-09-13 01:58:00.513309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3159ca256c18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('trusted_devices', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trusted_devices')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
