"""add ZAP technical fields to Vulnerability model

Revision ID: 4f0795be5b59
Revises: df8cce475481
Create Date: 2025-10-09 02:14:58.460750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0795be5b59'
down_revision = 'df8cce475481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('param', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attack', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('otherinfo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('references', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cweid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wascid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_column('wascid')
        batch_op.drop_column('cweid')
        batch_op.drop_column('references')
        batch_op.drop_column('confidence')
        batch_op.drop_column('otherinfo')
        batch_op.drop_column('attack')
        batch_op.drop_column('param')
        batch_op.drop_column('method')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
