"""Add shared notifications and sender tracking

Revision ID: effad42d3deb
Revises: c21b41b173e0
Create Date: 2025-09-24 02:23:02.710460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = 'effad42d3deb'
down_revision = 'c21b41b173e0'
branch_labels = None
depends_on = None

def upgrade():
    # Check if the table already exists
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    tables = inspector.get_table_names()

    if 'shared_notification' not in tables:
        op.create_table(
            'shared_notification',
            sa.Column('notification_id', sa.Integer(), nullable=False),
            sa.Column('recipient_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['notification_id'], ['notification.id']),
            sa.ForeignKeyConstraint(['recipient_id'], ['user.id']),
            sa.PrimaryKeyConstraint('notification_id', 'recipient_id')
        )

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.drop_column('recipient_id')
        batch_op.create_foreign_key('fk_notification_sender_id_user', 'user', ['sender_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])
        batch_op.drop_column('sender_id')

    op.drop_table('shared_notification')
    # ### end Alembic commands ###
